name: 4d_scaffold
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults

dependencies:
  - cudatoolkit=11.6
  - plyfile=1.0.3
  - python=3.8.20
  - pip=24.2
  - pytorch=2.0.1
  - torchaudio=2.0.2
  - torchvision=0.15.2
  - pytorch-scatter
  - tqdm

  - pip:
    - einops
    - natsort
    - wandb
    - lpips
    - laspy
    - opencv-python
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn